# NumPy Indexing and Selection

we will discuss how to select elements or groups of elements from an array.

In [33]:
import numpy as np

In [34]:
#Creating sample array
arr = np.arange(0,11)

In [35]:
#Show
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

## Bracket Indexing and Selection
The simplest way to pick one or some elements of an array looks very similar to python lists:

In [36]:
#Get a value at an index
arr[8]

8

In [37]:
#Get values in a range
arr[1:5]

array([1, 2, 3, 4])

In [38]:
#Get values in a range
arr[0:5]

array([0, 1, 2, 3, 4])

In [39]:
arr[:5]

array([0, 1, 2, 3, 4])

## Broadcasting / broad-assigning

NumPy arrays differ from normal Python lists because of their ability to broadcast. With lists, you can only reassign parts of a list with new parts of the same size and shape. That is, if you wanted to replace the first 5 elements in a list with a new value, you would have to pass in a new 5 element list. With NumPy arrays, you can broadcast a single value across a larger set of values:

In [40]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [41]:
#Setting a value with index range (Broadcasting)
arr[0:5]=100

#Show
print(arr)

#broadcasting is not available for lists
lst= [1,2,3,4,5,6,7] #python list

lst[0:3] = 100

[100 100 100 100 100   5   6   7   8   9  10]


TypeError: can only assign an iterable

In [42]:
# Reset array, we'll see why I had to reset in  a moment
arr = np.arange(0,11)

#Show
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [43]:
#Important notes on Slices
slice_of_arr = arr[0:6]

#Show slice
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [44]:
#Change Slice
slice_of_arr[:]=99

#Show Slice again
slice_of_arr

array([99, 99, 99, 99, 99, 99])

Now note the changes also occur in our original array!

In [45]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

Data is not copied, it's a view of the original array! This avoids memory problems!

In [46]:
#To get a copy, need to be explicit
arr_copy = arr.copy()

arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [47]:
arr_copy[0:2] = 55
arr_copy
# arr

array([55, 55, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [48]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

## Indexing a 2D array (matrices)

The general format is **arr_2d[row][col]** or **arr_2d[row,col]**. I recommend using the comma notation for clarity.

In [49]:
arr3= [1,2,3,4,5,6,7]
print(arr3[0:6])
print(arr3[0:-1])

[1, 2, 3, 4, 5, 6]
[1, 2, 3, 4, 5, 6]


In [51]:
arr_2d = np.array(([5,10,15],[20,25,30],[35,40,45])) #3X3

#Show
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [52]:
#Indexing row
arr_2d[1]

array([20, 25, 30])

In [54]:
# Format is arr_2d[row][col] or arr_2d[row,col]

# Getting individual element value
arr_2d[1][0]

20

In [55]:
# Getting individual element value
arr_2d[1,0]

20

In [56]:
# 2D array slicing

#Shape (2,2) from top right corner
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [58]:
print(arr_2d)

arr_2d[1:3,1:3]

[[ 5 10 15]
 [20 25 30]
 [35 40 45]]


array([[25, 30],
       [40, 45]])

In [24]:
#Shape bottom row
arr_2d[2]

array([35, 40, 45])

In [59]:
#Shape bottom row
arr_2d[2,:]
arr_2d[2][:]

array([35, 40, 45])

In [61]:
arr_2d[2][:]

array([35, 40, 45])

## More Indexing Help
Indexing a 2D matrix can be a bit confusing at first, especially when you start to add in step size. Try google image searching *NumPy indexing* to find useful images, like this one:

<img src= 'numpy_indexing.png' width=500/> Image source: http://www.scipy-lectures.org/intro/numpy/numpy.html

## Conditional Selection --> filtering

Let's briefly go over how to use brackets for selection based off of comparison operators.

In [62]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [27]:
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [28]:
bool_arr = arr>4

In [29]:
bool_arr

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [30]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [31]:
arr[arr>2]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [32]:
x = 2
arr[arr>x]


array([ 3,  4,  5,  6,  7,  8,  9, 10])

# Great Job!
